-- 站点协同
CREATE TABLE `form_data` (
`id` bigint(19) NOT NULL AUTO_INCREMENT,
`order_no` varchar(32) NOT NULL COMMENT '运单号',
`registration_sheng` varchar(32) DEFAULT NULL COMMENT '登记省',
`registration_szd` varchar(32) DEFAULT NULL COMMENT '登记区县',
`registration_site` varchar(60) NOT NULL COMMENT '登记站点',
`registration_mc` varchar(255) NOT NULL COMMENT '登记站点名称',
`registration_up` varchar(32) NOT NULL COMMENT '发起站点上级',
`deal_sheng` varchar(32) DEFAULT NULL COMMENT '处理省',
`deal_szd` varchar(32) DEFAULT NULL COMMENT '处理区县 ',
`deal_site` varchar(32) NOT NULL DEFAULT 'headless' COMMENT '处理站点（存放站点编码，若存放信息为headless代表无头件）',
`deal_mc` varchar(255) DEFAULT NULL COMMENT '接收站点名称',
`deal_up` varchar(32) DEFAULT NULL COMMENT '接收，处理站点上级站点',
`registration_user` varchar(32) NOT NULL COMMENT '登记人名称',
`registration_gh` varchar(32) DEFAULT NULL COMMENT '登记人工号',
`receive_type` tinyint(4) DEFAULT '0' COMMENT '0发送，1接收，2知会',
`notify_site` varchar(32) NOT NULL DEFAULT '' COMMENT '知会站点',
`notify_mc` varchar(255) DEFAULT NULL COMMENT '知会站点名称',
`notify_up` varchar(32) NOT NULL DEFAULT '' COMMENT '知会站点上级站点',
`deal_user` varchar(32) DEFAULT NULL COMMENT '处理人名称',
`deal_gh` varchar(32) DEFAULT NULL COMMENT '处理人工号',
`order_code` tinyint(4) DEFAULT NULL COMMENT '问题件类型编码',
`order_type` varchar(60) DEFAULT NULL COMMENT '问题件类型（属于什么类型的问题件）',
`mail_type` varchar(32) DEFAULT NULL COMMENT '快件类型',
`order_state` text COMMENT '情况说明',
`order_intervention` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否为总部介入 默认0 0：否 1是',
`order_resource` varchar(32) DEFAULT NULL COMMENT '问题件来源(巴枪扫描：scanning 人工录入：entering)',
`order_claim` varchar(32) DEFAULT 'noclaim' COMMENT '认领状态默认未认领noclaim 可选类型：noclaim未认领 inclaim:认领中 claimed:已认领 cancel：已撤销',
`order_status` varchar(32) NOT NULL DEFAULT 'reply' COMMENT '问题件处理状态默认待回复（待回复：reply 处理中：process 已结案：settled 投诉处理中(保证其排序能够排到第一位)：complain）',
`is_complain` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否投诉单(0否，1是)',
`is_process` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否回复（0未回复，1已回复）',
`order_score` tinyint(2) DEFAULT NULL COMMENT '问题件处理及时性评分默认1 0：不满意 1满意',
`score_reason` tinytext COMMENT '不满意原因',
`order_star` tinyint(2) DEFAULT NULL COMMENT '满意度评分星星 0:0颗星 1：一颗星 2:2颗星 3:3颗星',
`send_name` varchar(32) DEFAULT NULL COMMENT '发件人姓名',
`send_prov` varchar(60) DEFAULT NULL COMMENT '发件人省份',
`send_city` varchar(60) DEFAULT NULL COMMENT '发件人城市',
`send_area` varchar(100) DEFAULT NULL COMMENT '发件人区域',
`send_detail` varchar(255) DEFAULT NULL COMMENT '发件人详细地址',
`send_phone` varchar(32) DEFAULT NULL COMMENT '发件人手机',
`rece_name` varchar(32) DEFAULT NULL COMMENT '收件人名字',
`rece_prov` varchar(60) DEFAULT NULL COMMENT '收件人省份',
`rece_city` varchar(60) DEFAULT NULL COMMENT '收件人城市',
`rece_area` varchar(100) DEFAULT NULL COMMENT '收件人区域',
`rece_detail` varchar(255) DEFAULT NULL COMMENT '收件人详细地址',
`rece_phone` varchar(32) DEFAULT NULL COMMENT '收件人电话',
`order_pack` varchar(32) DEFAULT NULL COMMENT '快件包装',
`order_shape` varchar(32) DEFAULT NULL COMMENT '问题件形状',
`order_weight` varchar(32) DEFAULT NULL COMMENT '快件重量',
`order_brand` varchar(60) DEFAULT NULL COMMENT '快件品牌',
`order_texture` varchar(32) DEFAULT NULL COMMENT '问题件材质',
`order_size` varchar(32) DEFAULT NULL COMMENT '快件体积',
`order_color` varchar(32) DEFAULT NULL COMMENT '快件颜色',
`order_pic` varchar(355) DEFAULT NULL COMMENT '问题件附件',
`carriage_type` tinyint(2) DEFAULT NULL COMMENT '运输方式',
`depart_prove` tinytext COMMENT '发车凭证',
`order_enclosure` tinytext COMMENT '无头件认领附件',
`is_delete` tinyint(2) NOT NULL,
`deal_method` varchar(255) DEFAULT NULL COMMENT '无头件认领处理方法',
`cancel_user` varchar(36) DEFAULT NULL COMMENT '无头件撤销登记操作人工号',
`cancel_regist_reason` tinytext COMMENT '无头件取消登记原因',
`limit_respond_time` datetime NOT NULL COMMENT '回复截止时间',
`create_time` datetime NOT NULL COMMENT '巴枪扫描或发布时间',
`update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`freight_no` varchar(32) DEFAULT NULL COMMENT '货运单号',
`regist_site_deal` tinyint(4) NOT NULL DEFAULT '0' COMMENT '发布站点是否查看状态 0无需处理1未读2已读',
`deal_site_deal` tinyint(4) NOT NULL DEFAULT '0' COMMENT '接收站点是否查看状态 0无需处理1未读2已读',
PRIMARY KEY (`id`, `order_no`, `create_time`),
UNIQUE KEY `idx_roct` (
`registration_site`,
`order_no`,
`order_code`,
`order_type`,
`create_time`
),
KEY `order_no` (`order_no`),
KEY `order_code` (`order_code`),
KEY `create_time` (`create_time`),
KEY `deal_up_time_status` (`deal_up`, `create_time`, `order_status`),
KEY `idx02_form_data` (`registration_site`, `order_status`, `create_time`),
KEY `deal_site_time_status` (`deal_site`, `create_time`, `order_status`),
KEY `indx_form_data` (
`registration_site`,
`regist_site_deal`,
`deal_site`
),
KEY `indx02_form_data` (`deal_site`, `deal_site_deal`, `order_code`),
KEY `idx_site_time` (`registration_site`, `create_time`)
) ENGINE = InnoDB AUTO_INCREMENT = 6377029366 DEFAULT CHARSET = utf8 COMMENT = '表单数据提交表（字段跟element表记录中name值对应，动态更新，本表中的sheng指的是业务省）'
;

-- 投诉理赔工单
CREATE TABLE `themis_complain` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `complain_id` varchar(64) DEFAULT NULL COMMENT '投诉单id',
  `customer_code` varchar(64) NOT NULL COMMENT '客户编码',
  `call_no` varchar(200) DEFAULT NULL,
  `order_code` varchar(64) DEFAULT NULL COMMENT '物流订单编码',
  `third_order_code` varchar(64) DEFAULT NULL COMMENT '第三方物流订单编码',
  `third_task_id` varchar(64) DEFAULT NULL COMMENT '三方任务ID',
  `bill_code` varchar(64) DEFAULT NULL COMMENT '运单号',
  `incoming_identity` tinyint(4) DEFAULT NULL COMMENT '来电人身份：1-投诉人，2-发件人，3-收件人，4-第三方，5-其他站点',
  `business_type` tinyint(4) DEFAULT NULL COMMENT '工单业务类型 10-投诉单 20-理赔单  30-预警单 40-咨询单',
  `complain_type_id` bigint(20) DEFAULT NULL COMMENT '客户投诉原因id',
  `duty_type_id` int(11) DEFAULT NULL COMMENT '责任类型id',
  `complain_source` varchar(11) DEFAULT NULL COMMENT '投诉来源：详情见sys_comp_resource_time_zone表',
  `complain_time` datetime DEFAULT NULL COMMENT '投诉时间',
  `complain_site_id` bigint(20) DEFAULT NULL COMMENT '被投诉网点id(原始责任网点)',
  `duty_site_id` bigint(20) DEFAULT NULL COMMENT '责任网点id',
  `dispose_site_id` bigint(20) DEFAULT NULL COMMENT '待处理网点id',
  `status` tinyint(4) DEFAULT '1' COMMENT '操作状态 0 初始化  1 处理中 2处理成功 5处理失败',
  `dist_time` datetime DEFAULT NULL COMMENT '分配时间',
  `del_flag` smallint(1) DEFAULT '0' COMMENT '0否1是 是否逻辑删除',
  `complain_content` text COMMENT '投诉内容',
  `deal_user_id` bigint(20) DEFAULT NULL COMMENT '实际处理人id',
  `deal_user_name` varchar(64) DEFAULT NULL COMMENT '实际处理人name',
  `belong_user_id` bigint(20) DEFAULT NULL COMMENT '工单归属人id',
  `belong_user_name` varchar(64) DEFAULT NULL COMMENT '工单归属人名称',
  `take_user_id` bigint(20) DEFAULT NULL COMMENT '抢单人id',
  `take_user_name` varchar(64) DEFAULT NULL COMMENT '抢单人name',
  `take_time` datetime DEFAULT NULL COMMENT '抢单时间',
  `priority` tinyint(4) DEFAULT NULL COMMENT '优先级',
  `score_result` tinyint(2) DEFAULT '0' COMMENT '评分结果：0-未评分，1-不满意，2-满意',
  `score_time` datetime DEFAULT NULL COMMENT '评分时间',
  `modifier` varchar(64) DEFAULT NULL COMMENT '修改人name',
  `modifier_id` bigint(20) DEFAULT NULL COMMENT '修改人id',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人名称',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_site_id` bigint(20) DEFAULT NULL COMMENT '创建网点id',
  `repeat_status` tinyint(4) DEFAULT NULL COMMENT '重复单 1  二次诉求 2  二次申诉 3 普通单为空   4-理赔单重新开启',
  `origin_complain_id` varchar(64) DEFAULT NULL COMMENT '原complainId',
  `status_tag` tinyint(4) DEFAULT NULL COMMENT '状态标记 1,"网点处理中"   2,"总部协商"\r\n3,"待客户提供资料"\r\n4,"需及时跟踪"\r\n5,"私了中待核对"',
  `warn_note` varchar(20) DEFAULT NULL COMMENT '预警单备注',
  `order_source` varchar(64) DEFAULT NULL,
  `complain_site_name` varchar(64) DEFAULT '' COMMENT '被投诉网点名称',
  `duty_site_name` varchar(64) DEFAULT '' COMMENT '责任网点名称',
  `dispose_site_name` varchar(64) DEFAULT '' COMMENT '处理网点名称',
  `province_code` varchar(6) DEFAULT '' COMMENT '省code 跟处理网点dispose_site_id相关，总部默认为空',
  `province_site_id` bigint(20) DEFAULT NULL COMMENT '省客服部网点id 跟处理网点dispose_site_id相关，总部默认为空',
  `parent_site_id` bigint(20) DEFAULT NULL COMMENT '一级公司网点id（跟处理网点dispose_site_id相关,分部、服务部为上级公司，一级网点默认自己）',
  `duty_parent_site_id` bigint(20) DEFAULT NULL COMMENT '一级公司网点id（跟责任网点duty_site_id相关,分部、服务部为上级公司，一级网点默认自己）',
  `cainiao_biz_code` bigint(20) DEFAULT NULL COMMENT '菜鸟咨询单bizcode',
  `auto_pending` tinyint(2) NOT NULL DEFAULT '0' COMMENT '自动结单标识，0 否  1是',
  `bill_order_source` tinyint(4) DEFAULT NULL COMMENT '订单来源 1-菜鸟订单 2-京东订单 3-拼多多订单 4-拼多多国际订单 5-白马系统订单 6-云集订单 7-散单/二维码订单',
  `bill_goods_type` varchar(64) DEFAULT '' COMMENT '物品类别',
  `statement_count` tinyint(2) DEFAULT '0' COMMENT '结单次数',
  `salesman_id` bigint(12) DEFAULT '0' COMMENT '业务员id',
  `salesman_name` varchar(64) DEFAULT '' COMMENT '业务员名称',
  `tag_code` varchar(64) DEFAULT '' COMMENT '标签编码',
  `virtual_number_status` smallint(1) NOT NULL DEFAULT '0' COMMENT '是否虚拟号 0否1是',
  `sort_tag` varchar(128) NOT NULL DEFAULT '' COMMENT '星级标签',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `idx_bill_code` (`bill_code`,`status`,`del_flag`,`business_type`) USING BTREE,
  UNIQUE KEY `idx_complain_id` (`complain_id`,`del_flag`,`business_type`,`status`) USING BTREE,
  KEY `idx_belong_id_time` (`belong_user_id`,`create_time`),
  KEY `idx_origin_complain_id` (`origin_complain_id`) USING BTREE,
  KEY `idx_third_order_code` (`third_order_code`) USING BTREE,
  KEY `idx_complain_time` (`business_type`,`del_flag`,`complain_time`),
  KEY `idx_create_time` (`business_type`,`del_flag`,`create_time`),
  KEY `idx_parent_site_id` (`parent_site_id`,`business_type`,`del_flag`),
  KEY `idx_duty_parent_site_id` (`duty_parent_site_id`,`business_type`,`del_flag`),
  KEY `idx_customer_code_eCSt` (`customer_code`),
  KEY `idx_salesman_id_dist_time` (`salesman_id`,`dist_time`) USING BTREE,
  KEY `idx_complain_source_business_type_status_modify_time` (`complain_source`,`business_type`,`status`,`modify_time`),
  KEY `idx_dispose_site_id_deal_user_id_status` (`dispose_site_id`,`deal_user_id`,`status`),
  KEY `idx_duty_site_id_complain_time` (`duty_site_id`,`complain_time`),
  KEY `idx_disposeSiteId_distTime` (`dispose_site_id`,`business_type`,`dist_time`)
) ENGINE=InnoDB AUTO_INCREMENT=107339545 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='工单表'
;

-- 咨询工单
CREATE TABLE `themis_complain` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `complain_id` varchar(64) NOT NULL COMMENT '投诉单id',
  `customer_code` varchar(64) NOT NULL DEFAULT '' COMMENT '客户编码',
  `call_no` varchar(200) NOT NULL DEFAULT '' COMMENT '客户电话',
  `order_code` varchar(64) NOT NULL DEFAULT '' COMMENT '物流订单编码',
  `bill_code` varchar(64) NOT NULL COMMENT '运单号',
  `incoming_identity` tinyint(4) NOT NULL DEFAULT '1' COMMENT '来电人身份：1-投诉人，2-发件人，3-收件人，4-第三方，5-其他站点',
  `business_type` tinyint(4) NOT NULL COMMENT '工单业务类型 40-咨询单',
  `complain_type_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '客户投诉原因id',
  `duty_type_id` int(11) NOT NULL DEFAULT '0' COMMENT '责任类型id',
  `complain_source` varchar(64) NOT NULL DEFAULT '' COMMENT '投诉来源：详情见sys_comp_resource_time_zone表',
  `complain_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '投诉时间',
  `duty_site_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '责任网点id',
  `dispose_site_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '处理网点id',
  `overflow_hq_site_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '溢出到总部的机构id',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '操作状态 0 初始化  1 处理中 2处理成功 5处理失败',
  `process_status` tinyint(4) NOT NULL DEFAULT '10' COMMENT '流程状态：10待分单，2x(20网点、21省、22总部、23省和总部)待接单，30待回复，40已结束',
  `overflow_time` datetime DEFAULT NULL COMMENT '溢出时间',
  `real_overflow_time` datetime DEFAULT NULL COMMENT '实际溢出时间 网点溢出到总部或者省公司，有此值',
  `dist_time` datetime DEFAULT NULL COMMENT '分配时间',
  `deal_user_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '实际处理人id',
  `deal_user_name` varchar(64) NOT NULL DEFAULT '' COMMENT '实际处理人name',
  `belong_user_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '工单归属人id',
  `belong_user_name` varchar(64) NOT NULL DEFAULT '' COMMENT '工单归属人名称',
  `repeat_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '普通单0 1重复单 2二次诉求 3二次申诉 4理赔单重新开启',
  `complain_site_name` varchar(64) NOT NULL DEFAULT '' COMMENT '被投诉网点名称',
  `duty_site_name` varchar(64) NOT NULL DEFAULT '' COMMENT '责任网点名称',
  `dispose_site_name` varchar(64) NOT NULL DEFAULT '' COMMENT '处理网点名称',
  `province_code` varchar(6) NOT NULL DEFAULT '' COMMENT '省code 跟处理网点dispose_site_id相关，总部默认为空',
  `province_site_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '省客服部网点id 跟处理网点dispose_site_id相关，总部默认为空',
  `bill_order_source` tinyint(4) NOT NULL DEFAULT '0' COMMENT '订单来源 1-菜鸟订单 2-京东订单 3-拼多多订单 4-拼多多国际订单 5-白马系统订单 6-云集订单 7-散单/二维码订单',
  `bill_goods_type` varchar(64) NOT NULL DEFAULT '' COMMENT '物品类别',
  `modifier` varchar(64) NOT NULL DEFAULT '' COMMENT '修改人name',
  `modifier_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '修改人id',
  `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人名称',
  `creator_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建人id',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_site_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建网点id',
  `del_flag` smallint(1) NOT NULL DEFAULT '0' COMMENT '0否1是 是否逻辑删除',
  `allot_count` tinyint(10) NOT NULL DEFAULT '1' COMMENT '下发次数',
  `complain_site_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '被投诉网点id',
  `parent_site_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '一级公司网点id（跟处理网点dispose_site_id相关,分部、服务部为上级公司，一级网点默认自己）',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `idx_complain_id` (`complain_id`) USING BTREE,
  KEY `idx_bill_code` (`bill_code`) USING BTREE,
  KEY `idx_dispose_site_id` (`dispose_site_id`,`dist_time`,`process_status`,`del_flag`) USING BTREE,
  KEY `idx_overflow_hq_site_id` (`overflow_hq_site_id`,`dist_time`,`process_status`) USING BTREE,
  KEY `idx_create_time_site_id` (`create_time`,`dispose_site_id`,`belong_user_id`) USING BTREE,
  KEY `idx_province_site_id` (`province_site_id`,`dist_time`,`del_flag`) USING BTREE,
  KEY `idx_duty_site_id` (`duty_site_id`,`dist_time`,`complain_source`,`complain_type_id`),
  KEY `idx_modify_time_status` (`modify_time`,`business_type`,`process_status`) USING BTREE,
  KEY `idx_complain_time_site_id` (`complain_time`,`dispose_site_id`,`process_status`,`belong_user_id`),
  KEY `idx_parent_site_time` (`parent_site_id`,`complain_time`,`process_status`,`complain_type_id`),
  KEY `idx_overflow_hq_site_complain_time` (`overflow_hq_site_id`,`process_status`,`complain_time`,`complain_source`),
  KEY `idx_dispose_site_complain_time` (`dispose_site_id`,`process_status`,`complain_time`,`complain_source`)
) ENGINE=InnoDB AUTO_INCREMENT=101341324 DEFAULT CHARSET=utf8mb4 COMMENT='工单表'
;

-- 散单工单
CREATE TABLE `work_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `work_order_id` varchar(32) NOT NULL DEFAULT '' COMMENT '工单id',
  `bill_code` varchar(32) NOT NULL DEFAULT '' COMMENT '运单号',
  `complainant` varchar(128) DEFAULT '' COMMENT '投诉人',
  `complainant_contact` varchar(128) DEFAULT NULL COMMENT '投诉人电话',
  `service_id` varchar(128) DEFAULT '' COMMENT '抖音业务线id',
  `ticket_id` varchar(128) DEFAULT '' COMMENT '抖音工单ID',
  `tiktok_source` varchar(128) DEFAULT '' COMMENT '抖音来源',
  `service_type` varchar(64) DEFAULT '' COMMENT '服务类型',
  `ticket_first_type` varchar(64) DEFAULT NULL COMMENT '抖音一级分类',
  `ticket_second_type` varchar(64) DEFAULT '' COMMENT '抖音二级分类(投诉原因)',
  `ticket_third_type` varchar(64) DEFAULT '' COMMENT '抖音三级分类(责任类型)',
  `complain_time` datetime DEFAULT NULL COMMENT '投诉时间',
  `dist_time` datetime DEFAULT NULL COMMENT '分配时间',
  `feedback_time` datetime DEFAULT NULL COMMENT '反馈时间',
  `handle_response` tinyint(4) DEFAULT '0' COMMENT '处理结果，1认责，2不认则',
  `maintain_ticket_second_type` varchar(128) DEFAULT '' COMMENT '仲裁二级类型id',
  `maintain_ticket_third_type` varchar(128) DEFAULT '' COMMENT '仲裁三级类型',
  `maintain_ticket_first_type` varchar(128) DEFAULT '' COMMENT '仲裁一级类型id',
  `biz_status` int(1) DEFAULT '-1' COMMENT '字节业务状态： 1 待处理 2 待申诉 3 一次仲裁不成立 4 二次仲裁成立 5 二次仲裁不成立',
  `send_time` datetime DEFAULT NULL COMMENT '下发时间（Bizstatus 为待申诉的工单下发时间）',
  `dispose_site_id` bigint(20) DEFAULT '0' COMMENT '当前处理网点id',
  `dispose_site_name` varchar(64) DEFAULT '' COMMENT '处理站点名称',
  `deal_user_id` varchar(32) DEFAULT '' COMMENT '当前处理人id',
  `deal_user_name` varchar(32) DEFAULT '' COMMENT '处理人名称',
  `duty_site_id` bigint(20) DEFAULT '0' COMMENT '责任网点id',
  `duty_site_name` varchar(128) DEFAULT '' COMMENT '责任网点名称',
  `overflow_time` datetime DEFAULT NULL COMMENT '预计溢出时间',
  `real_overflow_time` datetime DEFAULT NULL COMMENT '实际溢出时间',
  `work_order_status` int(11) DEFAULT '10' COMMENT '工单状态(10待分单，20网点待接单，21省公司待接单，22总部待接单，30网点待反馈，31省公司待反馈，32总部待反馈，41省公司待审核，42总部待审核，52总部待申诉，100结束)',
  `parent_site_id` bigint(20) DEFAULT '0' COMMENT '上级网点编码',
  `province_code` int(10) DEFAULT '0' COMMENT '业务省code',
  `province_name` varchar(32) DEFAULT '' COMMENT '业务省名称',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_id` bigint(20) DEFAULT '0' COMMENT '创建人id',
  `create_name` varchar(64) DEFAULT NULL COMMENT '创建人名称',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `modifier_id` bigint(20) DEFAULT '0' COMMENT '修改人id',
  `modifier_name` varchar(64) DEFAULT '' COMMENT '修改人名称',
  `del_flag` tinyint(4) DEFAULT '0' COMMENT '删除标记0正常，1已删除',
  `ticket_expire_time` datetime DEFAULT NULL COMMENT '超时时间',
  `work_order_source` varchar(32) DEFAULT 'douyin' COMMENT '工单来源:如douyin',
  `last_deal_user_id` varchar(32) DEFAULT '' COMMENT '最后处理人id',
  `last_deal_user_name` varchar(32) DEFAULT '' COMMENT '最后处理人名称',
  `last_audit_user_id` varchar(32) DEFAULT '' COMMENT '最后审核人id',
  `last_audit_user_name` varchar(32) DEFAULT '' COMMENT '最后审核人名称',
  `last_appeal_user_id` varchar(32) DEFAULT '' COMMENT '最后申诉人id',
  `last_appeal_user_name` varchar(32) DEFAULT '' COMMENT '最后申诉人名称',
  `branch_org_id` bigint(20) DEFAULT NULL COMMENT '责任网点orgid',
  `branch_org_name` varchar(64) DEFAULT NULL COMMENT '责任网点orgname',
  `parent_branch_org_id` bigint(20) DEFAULT NULL COMMENT '一级网点orgid',
  `parent_branch_org_name` varchar(64) DEFAULT NULL COMMENT '一级网点orgname',
  `province_org_id` bigint(20) DEFAULT NULL COMMENT '省公司orgid',
  `province_org_name` varchar(64) DEFAULT NULL COMMENT '省公司orgname',
  `head_org_id` bigint(20) DEFAULT NULL COMMENT '总部orgid',
  `head_org_name` varchar(64) DEFAULT NULL COMMENT '总部orgname',
  `last_deal_time` datetime DEFAULT NULL COMMENT '最后处理时间',
  `last_audit_time` datetime DEFAULT NULL COMMENT '最后审核时间',
  PRIMARY KEY (`id`),
  KEY `idx_bill_code` (`bill_code`),
  KEY `idx_ticket_id` (`ticket_id`),
  KEY `idx_work_order_id` (`work_order_id`),
  KEY `idx_modifytime` (`modify_time`),
  KEY `idx_createtime` (`create_name`)
) ENGINE=InnoDB AUTO_INCREMENT=41203 DEFAULT CHARSET=utf8mb4 COMMENT='工单主表'
;

-- 超市工单
CREATE TABLE `customer_complain` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `agent_id` int(11) DEFAULT NULL COMMENT '门店ID',
  `company` varchar(20) DEFAULT NULL COMMENT '快递公司',
  `ship_id` varchar(32) DEFAULT NULL COMMENT '运单号',
  `direction` tinyint(4) NOT NULL DEFAULT '0' COMMENT '工单类别: 0-正向 1-逆向',
  `state` tinyint(4) DEFAULT '0' COMMENT '总工单状态(0-待处理, 1-处理中, 2-已结单)',
  `status` tinyint(4) DEFAULT '0' COMMENT '客服处理状态(0-待接单 1-处理中 2-处理完结)',
  `visiable_state` tinyint(4) DEFAULT '0' COMMENT '门店状态(0-待处理中 1-处理中 2-已完结 3-已超时)',
  `type` tinyint(4) DEFAULT '1' COMMENT '工单类型(1-一次投诉  2-二次投诉)',
  `doubt` tinyint(1) DEFAULT '0' COMMENT '是否存疑(0-确定单子 1-不确定单子)',
  `handler_type` tinyint(4) DEFAULT '1' COMMENT '处理端类型(1-门店 2-客服)',
  `handler_id` int(11) DEFAULT NULL COMMENT '处理人',
  `handler_name` varchar(32) DEFAULT NULL COMMENT '处理人名',
  `complain_type` tinyint(4) DEFAULT '0' COMMENT '投诉人类型(0-其他 1-收件人 2-发送人)',
  `complain_user` varchar(64) DEFAULT NULL COMMENT '投诉人',
  `complain_phone` varchar(128) DEFAULT NULL COMMENT '工单提供人手机号',
  `complain_reason` tinyint(4) DEFAULT NULL COMMENT '客诉原因',
  `duty_type` smallint(16) DEFAULT NULL COMMENT '责任类型',
  `source` tinyint(4) unsigned DEFAULT '0' COMMENT '工单来源(0-老欢猫, 1-拼多多 2-微笑 3-坐席 4-抖音 5-韵享家 6-寄件工单)',
  `deal_status` tinyint(4) DEFAULT '0' COMMENT '首响状态（0：待首响，1：已首响，2：未首响）',
  `complain_content` varchar(512) DEFAULT '' COMMENT '工单信息',
  `create_user` int(11) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(32) DEFAULT NULL COMMENT '创建人名',
  `complain_time` datetime NOT NULL COMMENT '工单提交时间',
  `out_time` datetime DEFAULT NULL COMMENT '门店超时时间',
  `finish_time` datetime DEFAULT NULL COMMENT '完结时间',
  `del_flag` tinyint(1) DEFAULT '0' COMMENT '逻辑删除标志(0:正常 1:已删除)',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `assign_user_id` int(11) DEFAULT NULL COMMENT '领取人ID',
  `assign_user_name` varchar(32) DEFAULT '' COMMENT '领取人姓名',
  `oprate_time` datetime DEFAULT NULL COMMENT '处理时间',
  `quality_stauts` tinyint(4) DEFAULT '0' COMMENT '质检状态(0-未质检 1-质检通过 ,2-质检不通过)',
  `order_id` varchar(19) DEFAULT NULL COMMENT '订单号',
  `third_no` varchar(26) DEFAULT NULL COMMENT '三方单号',
  PRIMARY KEY (`id`),
  KEY `idx_ship_id` (`ship_id`) USING BTREE,
  KEY `idx_agent_id` (`agent_id`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE,
  KEY `idx_finish_time` (`finish_time`) USING BTREE,
  KEY `idx_complain_phone` (`complain_phone`) USING BTREE,
  KEY `idx_out_time` (`out_time`) USING BTREE,
  KEY `idx_third_no` (`third_no`) USING BTREE,
  KEY `idx_order_id` (`order_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=9752 DEFAULT CHARSET=utf8
;

-- 客户管家工单
CREATE TABLE `cm_ticket` (
`gmt_create` datetime NOT NULL COMMENT '创建时间',
`gmt_modified` datetime NOT NULL COMMENT '修改时间',
`month_create` datetime NOT NULL COMMENT '创建月份最后一天',
`ticket_no` varchar(40) NOT NULL COMMENT '工单编号',
`out_ticket_no` varchar(40) NOT NULL COMMENT '外部工单编号',
`mail_no` varchar(32) NOT NULL COMMENT '运单号',
`vip_code` varchar(32) NOT NULL COMMENT '客户VIP编码',
`branch_code` varchar(32) NOT NULL COMMENT '网点编码',
`platform_type` varchar(32) NOT NULL COMMENT '平台类型',
`shop_id` varchar(64) NOT NULL COMMENT '店铺id',
`create_time` datetime NOT NULL COMMENT '工单创建时间',
`type` tinyint(4) NOT NULL COMMENT '工单类型',
`sub_type` varchar(8) NOT NULL COMMENT '工单子类型',
`flag` tinyint(4) NOT NULL COMMENT '工单标记',
`handle_status` tinyint(4) NOT NULL COMMENT '工单处理状态',
`handle_result` varchar(128) DEFAULT NULL COMMENT '工单处理结果',
`reply_status` tinyint(4) NOT NULL COMMENT '工单回复状态',
`creator` varchar(512) NOT NULL COMMENT '工单 发起人',
`content` varchar(1024) DEFAULT NULL COMMENT '问题描述',
`source_system` varchar(32) NOT NULL COMMENT '来源系统',
`source` int(11) DEFAULT NULL COMMENT '工单来源 2 - 机器人',
`remark` varchar(256) DEFAULT NULL COMMENT '备注',
`attribute` text COMMENT '扩展字段',
`customer_rights` tinyint(1) NOT NULL DEFAULT '0' COMMENT '大客户权益0否1是',
`branch_remark` varchar(256) DEFAULT NULL COMMENT '网点备注',
PRIMARY KEY (`ticket_no`, `month_create`),
KEY `i_0` USING BTREE (`mail_no`, `type`, `sub_type`, `handle_status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT '工单表' PARTITION BY KEY(`ticket_no`) PARTITIONS 128 LOCAL PARTITION BY RANGE (month_create) INTERVAL 1 MONTH EXPIRE
AFTER
12 PRE ALLOCATE 3 PIVOTDATE NOW()
;

-- 客户管家回复工单
CREATE TABLE `cm_ticket_reply` (
`gmt_create` datetime NOT NULL COMMENT '创建时间',
`gmt_modified` datetime NOT NULL COMMENT '修改时间',
`month_create` datetime NOT NULL COMMENT '创建月份最后一天',
`reply_no` varchar(40) NOT NULL COMMENT '回复编号',
`ticket_no` varchar(40) NOT NULL COMMENT '工单编号',
`reply_time` datetime NOT NULL COMMENT '回复时间',
`mail_no` varchar(32) NOT NULL COMMENT '运单号',
`creator` varchar(32) NOT NULL COMMENT '回复创建人',
`content` varchar(1024) DEFAULT NULL COMMENT '回复内容',
`creator_type` tinyint(4) NOT NULL COMMENT '回复人类型',
`reply_type` tinyint(4) NOT NULL COMMENT '回复类型',
`remark` varchar(256) DEFAULT NULL COMMENT '备注',
`attach_file` varchar(2018) DEFAULT NULL COMMENT '附件列表',
`attribute` varchar(1024) DEFAULT NULL COMMENT '扩展字段',
`handle_type` int(11) DEFAULT '0' COMMENT '处理类型 0：已受理，1：进度查看，2：已完结',
PRIMARY KEY (`ticket_no`, `reply_no`, `month_create`),
GLOBAL INDEX `g_idx_mail_no` (`mail_no`) PARTITION BY KEY (`mail_no`) PARTITIONS 128,
KEY `auto_shard_key_ticket_no_reply_no` USING BTREE (`ticket_no`, `reply_no`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT '工单回复表' PARTITION BY HASH(`ticket_no`, `reply_no`) PARTITIONS 128 LOCAL PARTITION BY RANGE (month_create) INTERVAL 1 MONTH EXPIRE
AFTER
12 PRE ALLOCATE 3 PIVOTDATE NOW()
;

